import { FORMATIONS, type FormationType } from './formations';
import type { MentalityType } from '@/store/useTeamStore';

export interface SharedTeamSnapshot {
  version: 1 | 2;
  formation: FormationType;
  mentality: MentalityType;
  blindMode: boolean;
  competitionId?: string;
  captainId: string | null;
  squadName?: string;
  playerIds: (string | null)[];
}

const normalizeBase64 = (value: string) => {
  const base = value.replace(/-/g, '+').replace(/_/g, '/');
  return base.padEnd(base.length + ((4 - (base.length % 4)) % 4), '=');
};

const mentalities: MentalityType[] = ['Gegenpress', 'ParkTheBus', 'Balanced'];

const encodeBase64 = (value: string) => {
  const bytes = new TextEncoder().encode(value);
  let binary = '';

  for (let index = 0; index < bytes.length; index += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000));
  }

  return btoa(binary);
};

const decodeBase64 = (value: string) => {
  const binary = atob(normalizeBase64(value));
  const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));

  try {
    return new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  } catch {
    // Keep links generated by the previous Latin-1 implementation readable.
    return binary;
  }
};

const isFormation = (value: unknown): value is FormationType => {
  return typeof value === 'string' && FORMATIONS.some((formation) => formation.id === value);
};

const isMentality = (value: unknown): value is MentalityType => {
  return typeof value === 'string' && mentalities.includes(value as MentalityType);
};

export const encodeShareCode = (snapshot: SharedTeamSnapshot): string => {
  const json = JSON.stringify(snapshot);
  return encodeBase64(json).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/g, '');
};

export const decodeShareCode = (code: string): SharedTeamSnapshot | null => {
  if (!code || code.length > 8192 || !/^[A-Za-z0-9_-]+$/.test(code)) return null;

  try {
    const decoded = JSON.parse(decodeBase64(code)) as Partial<SharedTeamSnapshot>;
    if (
      (decoded.version !== 1 && decoded.version !== 2) ||
      !isFormation(decoded.formation) ||
      !isMentality(decoded.mentality) ||
      typeof decoded.blindMode !== 'boolean' ||
      (decoded.version === 2 && typeof decoded.competitionId !== 'string') ||
      (decoded.captainId !== null && typeof decoded.captainId !== 'string') ||
      (decoded.squadName !== undefined && typeof decoded.squadName !== 'string') ||
      !Array.isArray(decoded.playerIds) ||
      !decoded.playerIds.every((id) => id === null || typeof id === 'string')
    ) {
      return null;
    }

    return {
      version: decoded.version,
      formation: decoded.formation,
      mentality: decoded.mentality,
      blindMode: Boolean(decoded.blindMode),
      ...(typeof decoded.competitionId === 'string' ? { competitionId: decoded.competitionId } : {}),
      captainId: decoded.captainId ?? null,
      squadName: typeof decoded.squadName === 'string' ? decoded.squadName.slice(0, 32) : 'Efsane 11',
      playerIds: decoded.playerIds.slice(0, 11).concat(Array(11).fill(null)).slice(0, 11),
    };
  } catch {
    return null;
  }
};
